name: PR

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Setup deno"
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: "deno lint"
        run: make lint

      - name: "deno test"
        run: make test
