name: test workflow

on:
  pull_request:

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          map: |
            [
              {
                "name": "foo",
                "level": 0,
                "trim": true
              },
              {
                "level": 2,
                "trim": true
              },
              {
                "name": "heh",
                "level": 5
              }
            ]
          paths: src/* ./some/dir/metadata.yml some/dir/config.json /other/path/metadata.yml
