name: test workflow

on:
  pull_request:

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          testInput: "this is a test"
